apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-softglobal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/jonbull-group/backend-softglobal.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true